server.port: 8443

server.ssl:
  key-store-type: PKCS12
  key-store: classpath:keystore/edge.p12
  key-store-password: password
  key-alias: localhost

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring.cloud.gateway.routes:

  - id: oauth2-server
    uri: lb://authorization
    predicates:
      - Path=/oauth2/**

  - id: oauth2-login
    uri: lb://authorization
    predicates:
    - Path=/login/**

  - id: oauth2-error
    uri: lb://authorization
    predicates:
    - Path=/error/**

  - id: product-composite
    uri: lb://product-composite
    predicates:
      - Path=/product-composite/**

  - id: product-composite-swagger-ui
    uri: lb://product-composite
    predicates:
      - Path=/openapi/**

  - id: eureka-api
    uri: http://${app.eureka-server}:8761
    predicates:
      - Path=/eureka/api/{segment}
    filters:
      - SetPath=/eureka/{segment}

  - id: eureka-web-start
    uri: http://${app.eureka-server}:8761
    predicates:
      - Path=/eureka/web
    filters:
      - SetPath=/

  - id: eureka-web-other
    uri: http://${app.eureka-server}:8761
    predicates:
      - Path=/eureka/**
      
spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.authorization}:9999

spring.application.name: gateway

app:
  eureka-server: localhost
  authorization: localhost
  eureka-username: guest
  eureka-password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile:
        - docker
server:
  port: 8443

app:
  eureka-server: eureka
  authorization: authorization
